[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["crud_rest_api"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "crud_rest_api"
  org = "strb"
  version = "3.1.1"

